# Generated by Django 3.2.12 on 2023-01-25 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myappdjf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_emploi',
            name='languemaitrise',
            field=models.ManyToManyField(related_name='LangueUser', to='myappdjf.LangueMaitrise'),
        ),
        migrations.AlterField(
            model_name='languemaitrise',
            name='c_emploi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userlanguages', to='myappdjf.c_emploi'),
        ),
    ]
