# Generated by Django 3.2.12 on 2023-01-25 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myappdjf', '0002_auto_20230125_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='c_emploi',
            name='languemaitrise',
        ),
        migrations.AlterField(
            model_name='languemaitrise',
            name='c_emploi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chercheur', to='myappdjf.c_emploi'),
        ),
    ]
