# Generated by Django 3.2.12 on 2023-01-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappdjf', '0003_auto_20230125_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_emploi',
            name='adresse',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='c_emploi',
            name='description',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='c_emploi',
            name='experience',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='c_emploi',
            name='skills',
            field=models.CharField(default='', max_length=200),
        ),
    ]
