# Generated by Django 3.2.12 on 2023-02-10 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myappdjf', '0004_auto_20230127_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=20)),
                ('cv', models.FileField(upload_to='')),
                ('date_depot', models.DateTimeField(default=(2023, 2, 10, 17, 56, 4, 4, 41, 0))),
                ('c_emploi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myappdjf.c_emploi')),
            ],
        ),
    ]
