# Generated by Django 3.2.12 on 2023-02-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappdjf', '0006_auto_20230210_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travail',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='travail',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='travail',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='travail',
            name='description',
        ),
        migrations.RemoveField(
            model_name='travail',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='travail',
            name='salaire',
        ),
        migrations.RemoveField(
            model_name='travail',
            name='skills',
        ),
        migrations.AddField(
            model_name='travail',
            name='date',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='travail',
            name='link',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='travail',
            name='adresse',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='travail',
            name='entreprise',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='travail',
            name='image',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='travail',
            name='titre',
            field=models.CharField(default='', max_length=200),
        ),
    ]
