# Generated by Django 3.2.12 on 2023-02-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappdjf', '0007_auto_20230214_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='langue',
            name='description',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='langue',
            name='nom',
            field=models.CharField(default='', max_length=100),
        ),
    ]
